#!/usr/bin/env python3

# Simple test script to verify YAML format detection and processing

# Test YAML content for simple format (like Player.yaml)
simple_yaml = """
game: Friday Night Funkin
name: Player
description: Generated by Funkipelago for Friday Night Funkin

Friday Night Funkin:
  ticket_win_percentage: 50
  song_limit: 0
  shieldWeight: 0
  accrequirement: Any
  mods_enabled: false
  songList: [Ugh,Satin Panties,Beat Battle]
  progression_balancing: normal
  unlock_type: Per Song
  trapAmount: 0
  tutorialWeight: 0
  unlock_method: Song Completion
  graderequirement: Any
  ticket_percentage: 10
  accessibility: full
  deathlink: false
"""

# Test YAML content for weighted format (like Tester1.yaml)
weighted_yaml = """
name: Player{number}
description: Default Friday Night Funkin Template
game: Friday Night Funkin
requires:
  version: 0.6.2

Friday Night Funkin:
  progression_balancing:
    random: 0
    random-low: 0
    random-high: 0
    disabled: 0
    normal: 50
    extreme: 0

  accessibility:
    full: 50
    minimal: 0

  check_count:
    1: 50
    random: 0
    random-low: 0
    random-high: 0

  mods_enabled:
    'false': 50
    'true': 0

  song_limit:
    16: 50
    random: 0
    random-low: 0
    random-high: 0

  unlock_type:
    Per Song: 50

  unlock_method:
    Song Completion: 50

  deathlink:
    'false': 50
    'true': 0

  ticket_percentage:
    30: 50
    random: 0
    random-low: 0
    random-high: 0

  ticket_win_percentage:
    80: 50
    random: 0
    random-low: 0
    random-high: 0

  graderequirement:
    Any: 50

  accrequirement:
    Any: 50

  allowDupes:
    'false': 50
    'true': 0

  trapAmount:
    10: 50
    random: 0
    random-low: 0
    random-high: 0
"""

def test_yaml_formats():
    print("Testing YAML format detection and processing...")
    
    # Test simple format
    print("\n=== Testing Simple Format (Player.yaml style) ===")
    try:
        from .Yutautil import yutautil_APYaml
        
        simple_parser = yutautil_APYaml(simple_yaml)
        print(f"Format detected as weighted: {simple_parser.isWeightedFormat}")
        print(f"Game: {simple_parser.game}")
        print(f"Name: {simple_parser.name}")
        print(f"Description: {simple_parser.description}")
        print(f"Song limit: {simple_parser.settings.h.get('song_limit', 'Not found')}")
        print(f"Mods enabled: {simple_parser.settings.h.get('mods_enabled', 'Not found')}")
        print(f"Accessibility: {simple_parser.settings.h.get('accessibility', 'Not found')}")
        
    except Exception as e:
        print(f"Error testing simple format: {e}")
    
    # Test weighted format
    print("\n=== Testing Weighted Format (Tester1.yaml style) ===")
    try:
        weighted_parser = yutautil_APYaml(weighted_yaml)
        print(f"Format detected as weighted: {weighted_parser.isWeightedFormat}")
        print(f"Game: {weighted_parser.game}")
        print(f"Name: {weighted_parser.name}")
        print(f"Description: {weighted_parser.description}")
        print(f"Song limit: {weighted_parser.settings.h.get('song_limit', 'Not found')}")
        print(f"Mods enabled: {weighted_parser.settings.h.get('mods_enabled', 'Not found')}")
        print(f"Accessibility: {weighted_parser.settings.h.get('accessibility', 'Not found')}")
        print(f"Progression balancing: {weighted_parser.settings.h.get('progression_balancing', 'Not found')}")
        
    except Exception as e:
        print(f"Error testing weighted format: {e}")

if __name__ == "__main__":
    test_yaml_formats()
